import{Component,OnInit,inject,signal}from'@angular/core';import{CommonModule}from'@angular/common';import{FormsModule}from'@angular/forms';import{ActivatedRoute,Router,RouterLink}from'@angular/router';import{HttpErrorResponse}from'@angular/common/http';import{UserAdminService}from'../../../core/services/user-admin.service';import{User}from'../../../core/models/user.model';import{AuthService}from'../../../core/auth/auth.service';
@Component({selector:'app-utilisateur-detail',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./utilisateur-detail.component.html',styleUrls:['./utilisateur-detail.component.css']})
export class UtilisateurDetailComponent implements OnInit{private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly service=inject(UserAdminService);private readonly auth=inject(AuthService);user=signal<User|null>(null);isLoading=signal(true);isSaving=signal(false);errorMessage=signal<string|null>(null);successMessage=signal<string|null>(null);showDelete=signal(false);nom=signal('');prenom=signal('');email=signal('');role=signal('citizen');telephone=signal('');adresse=signal('');password=signal('');passwordConfirmation=signal('');formError=signal<string|null>(null);
ngOnInit(){this.load()}load(){const id=Number(this.route.snapshot.paramMap.get('id'));if(!Number.isFinite(id)){this.errorMessage.set('Identifiant utilisateur invalide.');this.isLoading.set(false);return}this.service.getById(id).subscribe({next:r=>{this.user.set(r.data);this.nom.set(r.data.nom);this.prenom.set(r.data.prenom);this.email.set(r.data.email);this.role.set(r.data.role);this.telephone.set(r.data.telephone||'');this.adresse.set(r.data.adresse||'');this.isLoading.set(false)},error:(e:HttpErrorResponse)=>{this.isLoading.set(false);this.errorMessage.set(e.status===404?'Utilisateur introuvable.':'Impossible de charger l’utilisateur.')}})}
save(){const u=this.user();if(!u)return;this.formError.set(null);if(this.password()&&this.password()!==this.passwordConfirmation()){this.formError.set('Les mots de passe ne correspondent pas.');return}this.isSaving.set(true);const p:any={nom:this.nom(),prenom:this.prenom(),email:this.email(),role:this.role(),telephone:this.telephone()||null,adresse:this.adresse()||null};if(this.password()){{p.password=this.password();p.password_confirmation=this.passwordConfirmation()}}this.service.update(u.id,p).subscribe({next:r=>{this.user.set(r.data);this.password.set('');this.passwordConfirmation.set('');this.isSaving.set(false);this.successMessage.set('Utilisateur mis à jour.')},error:(e:HttpErrorResponse)=>{this.isSaving.set(false);this.errorMessage.set(e.error?.message||'Mise à jour impossible.')}})}
canDelete(){const current=this.auth.currentUser();return !!current&&current.id!==this.user()?.id}
promptDelete(){if(this.canDelete())this.showDelete.set(true)}cancelDelete(){this.showDelete.set(false)}
delete(){const u=this.user();if(!u)return;this.service.delete(u.id).subscribe({next:()=>this.router.navigate(['/admin/utilisateurs']),error:(e:HttpErrorResponse)=>{this.showDelete.set(false);this.errorMessage.set(e.error?.message||'Suppression impossible.')}})}
roleLabel(r:string){return({admin:'Administrateur',agent:'Agent',citizen:'Citoyen'} as Record<string,string>)[r]||r}
}
