import{Component,OnInit,computed,inject,signal}from'@angular/core';import{CommonModule}from'@angular/common';import{FormsModule}from'@angular/forms';import{RouterLink}from'@angular/router';import{HttpErrorResponse}from'@angular/common/http';import{UserAdminService}from'../../../core/services/user-admin.service';import{User}from'../../../core/models/user.model';
@Component({selector:'app-utilisateurs-list',standalone:true,imports:[CommonModule,FormsModule,RouterLink],templateUrl:'./utilisateurs-list.component.html',styleUrls:['./utilisateurs-list.component.css']})
export class UtilisateursListComponent implements OnInit{private readonly service=inject(UserAdminService);users=signal<User[]>([]);meta=signal<any>(undefined);isLoading=signal(true);errorMessage=signal<string|null>(null);successMessage=signal<string|null>(null);search=signal('');roleFilter=signal('');showCreate=signal(false);nom=signal('');prenom=signal('');email=signal('');password=signal('');passwordConfirmation=signal('');role=signal<'admin'|'agent'|'citizen'>('citizen');telephone=signal('');adresse=signal('');formError=signal<string|null>(null);action=signal(false);
 filtered=computed(()=>{const q=this.search().trim().toLowerCase();return this.users().filter(u=>!q||[u.nom,u.prenom,u.email].join(' ').toLowerCase().includes(q))});
 ngOnInit(){this.load(1)}load(page:number){this.isLoading.set(true);this.service.getAll(page,{role:this.roleFilter(),nom:this.search()}).subscribe({next:r=>{this.users.set(r.data||[]);this.meta.set(r.meta);this.isLoading.set(false)},error:()=>{this.isLoading.set(false);this.errorMessage.set('Impossible de charger les utilisateurs.')}})}
 openCreate(){this.nom.set('');this.prenom.set('');this.email.set('');this.password.set('');this.passwordConfirmation.set('');this.role.set('citizen');this.telephone.set('');this.adresse.set('');this.formError.set(null);this.showCreate.set(true)}closeCreate(){this.showCreate.set(false)}
 create(){if(!this.nom().trim()||!this.prenom().trim()||!this.email().trim()||this.password().length<8){this.formError.set('Nom, prénom, email et mot de passe (8 caractères minimum) sont obligatoires.');return}if(this.password()!==this.passwordConfirmation()){this.formError.set('Les mots de passe ne correspondent pas.');return}this.action.set(true);this.service.create({nom:this.nom().trim(),prenom:this.prenom().trim(),email:this.email().trim(),password:this.password(),password_confirmation:this.passwordConfirmation(),role:this.role(),telephone:this.telephone()||null,adresse:this.adresse()||null}).subscribe({next:()=>{this.action.set(false);this.showCreate.set(false);this.successMessage.set('Utilisateur créé.');this.load(this.meta()?.current_page||1)},error:(e:HttpErrorResponse)=>{this.action.set(false);this.formError.set(e.error?.message||'Création impossible.')}})}
 roleLabel(r:string){return({admin:'Administrateur',agent:'Agent',citizen:'Citoyen'} as Record<string,string>)[r]||r}
}
