import{Component,OnInit,inject,signal}from'@angular/core';import{CommonModule}from'@angular/common';import{RouterLink}from'@angular/router';import{forkJoin}from'rxjs';import{GamificationService,LeaderboardRow,HistoriquePoint}from'../../core/services/gamification.service';
@Component({selector:'app-gamification-dashboard',standalone:true,imports:[CommonModule,RouterLink],template:`
<div class="page"><div class="head"><div><h1>Gamification</h1><p>Suivi des points citoyens et du classement.</p></div><div class="links"><a routerLink="/admin/gamification/classement" class="btn">Classement</a><a routerLink="/admin/gamification/historique-points" class="btn">Historique</a></div></div>
@if(error()){<div class="alert">{{error()}}</div>} @if(loading()){<div class="card state">Chargement...</div>} @else {<div class="kpis"><div class="card"><span>Points chargés</span><strong>{{total()}}</strong></div><div class="card"><span>Participants</span><strong>{{participants()}}</strong></div><div class="card"><span>Attributions chargées</span><strong>{{transactions()}}</strong></div></div><div class="grid"><section class="card"><div class="section-head"><h2>Top 10</h2><a routerLink="/admin/gamification/classement">Voir tout</a></div>@for(row of board().slice(0,10);track row.user.id){<div class="row"><b class="rank">{{row.rank}}</b><span>{{row.user.prenom}} {{row.user.nom}}</span><strong>{{row.total_points}} pts</strong></div>}@if(board().length===0){<p class="muted">Aucun participant.</p>}</section><section class="card"><div class="section-head"><h2>Dernières attributions</h2><a routerLink="/admin/gamification/historique-points">Voir tout</a></div>@for(item of history().slice(0,10);track item.id){<div class="row"><span><b>{{item.motif}}</b><small>{{item.user?.prenom}} {{item.user?.nom}} · {{item.date_attribution|date:'dd/MM/yyyy'}}</small></span><strong class="points">+{{item.nombre_points}}</strong></div>}@if(history().length===0){<p class="muted">Aucune attribution.</p>}</section></div>}</div>`,
styles:[` .page{display:flex;flex-direction:column;gap:1.2rem}.head{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.head h1{font-size:1.75rem;color:var(--slate-900)}.head p{color:var(--slate-500);margin-top:.35rem}.links{display:flex;gap:.5rem}.btn{display:inline-flex;padding:.65rem 1rem;border:1px solid var(--slate-200);border-radius:var(--radius-sm);background:#fff}.card{background:#fff;border:1px solid var(--slate-200);border-radius:var(--radius-md);box-shadow:var(--shadow-sm)}.kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.kpis .card{padding:1rem}.kpis span,.muted,small{color:var(--slate-500)}.kpis strong{display:block;font-size:1.7rem;margin-top:.2rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.section-head{display:flex;justify-content:space-between;padding:1rem 1.2rem;border-bottom:1px solid var(--slate-200)}.section-head h2{font-size:1rem}.section-head a{font-size:.82rem;color:var(--primary-700)}.row{display:flex;align-items:center;gap:.75rem;padding:.75rem 1.2rem;border-bottom:1px solid var(--slate-100)}.row:last-child{border-bottom:0}.row span{flex:1}.row small{display:block;margin-top:.15rem}.rank{width:28px;height:28px;border-radius:50%;background:var(--slate-100);display:grid;place-items:center}.points{color:var(--primary-700)}.alert{padding:.75rem 1rem;background:var(--danger-50);color:var(--danger-700);border-radius:var(--radius-sm)}.state{padding:4rem;text-align:center}@media(max-width:800px){.kpis,.grid{grid-template-columns:1fr}.head{flex-direction:column}.links{flex-wrap:wrap}}`]
})
export class GamificationDashboardComponent implements OnInit{
 private readonly service=inject(GamificationService);board=signal<LeaderboardRow[]>([]);history=signal<HistoriquePoint[]>([]);loading=signal(true);error=signal<string|null>(null);total=signal(0);participants=signal(0);transactions=signal(0);
 ngOnInit(){forkJoin({board:this.service.leaderboard(),history:this.service.history(1)}).subscribe({next:r=>{this.board.set(r.board.data||[]);this.history.set(r.history.data||[]);this.participants.set(r.board.meta?.count||0);this.total.set((r.history.data||[]).reduce((s,x)=>s+Number(x.nombre_points||0),0));this.transactions.set(r.history.meta?.total||r.history.data.length);this.loading.set(false)},error:()=>{this.loading.set(false);this.error.set('Impossible de charger les données de gamification.')}})}
}
